[package]
name = "armv4"
version = "0.1.0"
authors = ["bokuweb <bokuweb12@gmail.com>"]

[dependencies]
env_logger = "0.5.9"
log = "*"
byteorder = "1.2.2"
goblin = "0.0.15"
clippy = { version = "*", optional = true }